import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { randomUUID } from 'node:crypto';
import type { Bootstrap } from '../shared/types';

const origin = 'http://127.0.0.1:5174';

test('incoming webhook setup delivers as a scoped bot and rotates credentials from the interface', async ({ page }) => {
  const registered = await page.request.post('/api/auth/register', { headers: { Origin: origin }, data: { name: 'Bot Yöneticisi', email: `integration-ui-${randomUUID()}@example.invalid`, password: 'integration-browser-password', workspaceName: 'Bağlantı Ekibi' } });
  expect(registered.status()).toBe(200); const bootstrap = await registered.json() as Bootstrap;
  const channel = bootstrap.channels.find(channel => channel.kind === 'text')!;
  await page.goto('/');
  await expect(page.getByText('Her şey güncel', { exact: true })).toBeAttached();
  await page.getByRole('button', { name: 'Entegrasyonlar', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Entegrasyonlar', exact: true });
  await dialog.getByRole('button', { name: 'Entegrasyon ekle', exact: true }).click();
  await dialog.getByRole('radio', { name: /Gelen webhook/ }).check();
  await dialog.getByRole('textbox', { name: 'Botun adı', exact: true }).fill('Sürüm Botu');
  await dialog.getByRole('combobox', { name: 'Bildirim kanalı', exact: true }).selectOption(channel.id);
  const formAccessibility = await new AxeBuilder({ page }).include('.integration-create').analyze();
  expect(formAccessibility.violations.filter(violation => ['serious', 'critical'].includes(violation.impact || '')).map(violation => violation.id)).toEqual([]);
  await dialog.getByRole('button', { name: 'Entegrasyonu oluştur', exact: true }).click();
  const keyField = dialog.getByLabel('Entegrasyon anahtarı', { exact: true });
  await expect(keyField).toHaveAttribute('type', 'password');
  const secret = await keyField.inputValue(); const url = await dialog.getByRole('textbox', { name: 'Webhook adresi', exact: true }).inputValue();
  const deliver = (token: string, eventId: string) => page.request.post(url, { headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, data: { content: 'Sürüm kontrolü başarıyla tamamlandı.', eventId } });
  expect((await deliver(secret, 'first-release')).status()).toBe(201);
  expect((await deliver(secret, 'first-release')).status()).toBe(200);
  await page.evaluate(() => document.fonts.ready);
  const accessibility = await new AxeBuilder({ page }).include('.integrations-dialog').analyze();
  expect(accessibility.violations.filter(violation => ['serious', 'critical'].includes(violation.impact || '')).map(violation => ({ id: violation.id, nodes: violation.nodes.map(node => node.target) }))).toEqual([]);
  await page.screenshot({ path: 'artifacts/integration-setup-desktop.png', animations: 'disabled', mask: [keyField] });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);
  await page.screenshot({ path: 'artifacts/integration-setup-mobile.png', animations: 'disabled', mask: [keyField] });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await dialog.getByRole('button', { name: 'Anahtarı kaydettim, tamam', exact: true }).click();
  await expect(keyField).toHaveCount(0);
  await dialog.getByRole('button', { name: 'Entegrasyonları yenile', exact: true }).click();
  await expect(dialog.getByText(/Son başarılı bildirim:/)).toBeVisible();
  await dialog.getByRole('button', { name: 'Anahtarı yenile', exact: true }).click();
  await dialog.getByRole('button', { name: 'Anahtarı yenile ve göster', exact: true }).click();
  await expect(keyField).toHaveAttribute('type', 'password');
  const rotated = await keyField.inputValue(); expect(rotated).not.toBe(secret);
  expect((await deliver(secret, 'second-release')).status()).toBe(401);
  expect((await deliver(rotated, 'second-release')).status()).toBe(201);
  await dialog.getByRole('button', { name: 'Anahtarı kaydettim, tamam', exact: true }).click();
  await dialog.locator('.integration-row-actions').getByRole('button', { name: 'Kapat', exact: true }).click();
  await expect(dialog.locator('.integration-status')).toHaveText('Kapalı');
  expect((await deliver(rotated, 'third-release')).status()).toBe(404);
  await dialog.locator('.modal-heading').getByRole('button', { name: 'Kapat', exact: true }).click();
  await page.getByRole('button', { name: channel.name, exact: true }).click();
  await expect(page.locator('.message-text').filter({ hasText: 'Sürüm kontrolü başarıyla tamamlandı.' })).toHaveCount(2);
  const refreshed = await (await page.request.get('/api/auth/me')).json() as Bootstrap;
  const bot = refreshed.members.find(member => member.name === 'Sürüm Botu')!;
  expect(bot.isBot).toBe(true); expect(bot.role).toBe('guest');
});

test('GitHub setup supplies repository-specific instructions and a secret only on creation', async ({ page }) => {
  const response = await page.request.post('/api/auth/register', { headers: { Origin: origin }, data: { name: 'GitHub Yöneticisi', email: `github-ui-${randomUUID()}@example.invalid`, password: 'github-browser-password', workspaceName: 'GitHub Ekibi' } });
  expect(response.status()).toBe(200); await page.goto('/');
  await page.getByRole('button', { name: 'Entegrasyonlar', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Entegrasyonlar', exact: true });
  await dialog.getByRole('button', { name: 'Entegrasyon ekle', exact: true }).click();
  await dialog.getByRole('textbox', { name: 'GitHub deposu', exact: true }).fill('mola-test/project');
  await dialog.getByRole('button', { name: 'Entegrasyonu oluştur', exact: true }).click();
  await expect(dialog.getByRole('heading', { name: 'GitHub’da bağlantıyı tamamla', exact: true })).toBeVisible();
  await expect(dialog.getByRole('link', { name: 'GitHub webhook ayarlarını aç', exact: true })).toHaveAttribute('href', 'https://github.com/mola-test/project/settings/hooks/new');
  await expect(dialog.getByLabel('Entegrasyon anahtarı', { exact: true })).toHaveAttribute('type', 'password');
  await dialog.getByRole('button', { name: 'Anahtarı kaydettim, tamam', exact: true }).click();
  await dialog.getByRole('button', { name: 'Kurulum bilgileri', exact: true }).click();
  await expect(dialog.getByLabel('Entegrasyon anahtarı', { exact: true })).toHaveCount(0);
  await expect(dialog.getByText('Anahtar yeniden gösterilmez.', { exact: false })).toBeVisible();
});
